### ISSUE TITLE
feat: contribute

### ISSUE THREAD

**Issue by anicmarko9** [smart92dev/Chromaway#1]
Hello @smart92dev, is there any repository that I can contribute to? I'd like to contribute to something you are actively working at. I had trouble installing this repository, but if you have any recommendations on other your repositories, please just leave the link on this issue, and kindly close it 😁

**Comment by smart92dev** [comment]
@anicmarko9 
Hi, How are you today?
I could run this project on dev mode but have trouble in building. 
Some incompatibility exists. Node version: 17.8.0
btw, thank you for your contribution. Have a nice day :D
